services:
  - type: web
    name: 8769bet-frontend
    env: static
    branch: main
    rootDir: frontend
    buildCommand: echo "Using pre-built dist"
    staticPublishPath: dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: 8769bet-admin
    env: static
    branch: main
    rootDir: admin
    buildCommand: echo "Using pre-built dist"
    staticPublishPath: dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: 8769bet-backend
    env: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
