services:
  - type: web
    name: 8769bet-frontend
    env: static
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

  - type: web
    name: 8769bet-admin
    env: static
    branch: main
    rootDir: admin
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

  - type: web
    name: 8769bet-backend
    env: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install --production
    startCommand: node src/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3006
      - key: SUPABASE_URL
        value: https://rbcipnwwllkscomatqmc.supabase.co
